apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/archi1912/FlaskApp.git'   # <- your repo
    targetRevision: HEAD
    path: 'charts/flask-app'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app   # where the helm chart will be installed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
