apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/archi1912/FlaskApp.git'
    targetRevision: HEAD
    path: 'charts/postgres'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
