replicaCount: 1
image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

postgres:
  user: postgres
  password: postgres
  database: mydb

service:
  port: 5432
  
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
